@HomeWorkAPI_HostAddress = https://localhost:32778

GET {{HomeWorkAPI_HostAddress}}/schools/area?areacode=525003
Accept: application/json
###

GET {{HomeWorkAPI_HostAddress}}/schools/id?id=A125320600013
Accept: application/json
###

PUT {{HomeWorkAPI_HostAddress}}/user/create?username=alb&password=0
###
GET {{HomeWorkAPI_HostAddress}}/user/exists/abstract
###
